server:
  port: 9091
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minhateca
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
        
application-description: "@project.description@"
application-version: "@project.version@"